apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-vrbs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-vrbs
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-vrbs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-vrbs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-vrbs
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ixda-tenant/rhtap-demo-app/hacbs-test-project-vrbs@sha256:a7e5ba46761f2bdc1d137a8ad1cb9369c3d6f2519113f9a0d3b4e496d88aa852
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
