apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-vrbs
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ixda-tenant/rhtap-demo-app/hacbs-test-project-vrbs@sha256:a7e5ba46761f2bdc1d137a8ad1cb9369c3d6f2519113f9a0d3b4e496d88aa852
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
